files:
  - source: /**/*.md
    ignore:
      - /versions/**/*
      - /translated/**/*
      - LICENSE.md
      - README.md
    translation: /translated/%locale_with_underscore%/%original_path%/%original_file_name%
  - source: sidebar_translations.json
    translation: /translated/%locale_with_underscore%/%original_path%/%original_file_name%
