name: Run markdownlint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
      - '!translated/**'
      - '!versions/*/translated/**'
  workflow_dispatch: # Manual run

concurrency:
  group: markdownlint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-22.04

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - id: titlecase
        run: npm install markdownlint-rule-titlecase@v0.1.0

      - id: lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: .markdownlint-cli2.yaml
          globs: |
            **/*.md
            !translated/**
            !versions/*/translated/**
