name: Lint

on:
  pull_request:
    paths:
      - "**/*.md"
      - "!README.md"
      - "!translated/**"
      - "!versions/**"

concurrency:
  group: markdownlint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-24.04

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm install

      - id: lint
        uses: FabricMCBot/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8
        with:
          config: .markdownlint-cli2.yaml
          globs: |
            **/*.md
            !**/.git
            !**/node_modules
            !README.md
            !translated/**
            !versions/**
